-- PillReminder — every migration, in dependency order, as one script.
--
-- Generated by scripts/build-sql.js. Do not edit: change the individual files
-- and regenerate with `npm run sql`.
--
-- WHERE TO RUN THIS
--   Supabase Dashboard -> SQL Editor -> New query -> paste -> Run.
--
-- BEFORE YOU RUN IT
--   Enable pg_cron first: Database -> Extensions -> search "pg_cron" -> enable.
--   Without it the two retention jobs are skipped with a NOTICE rather than
--   failing, so the script still completes — you just get no server-side
--   pruning of dose history or expired verification codes.
--
-- Safe to re-run: every statement is guarded with `if not exists`,
-- `create or replace`, or a `drop ... if exists` first.


-- ========================================================================
-- schema.sql
-- ========================================================================

-- PillReminder — Supabase schema (Phase 0 + forward-declared tables)
-- Run this in the Supabase SQL Editor (Dashboard → SQL → New query → Run).
-- Safe to re-run: uses IF NOT EXISTS / CREATE OR REPLACE where possible.

-- ---------------------------------------------------------------------------
-- Extensions
-- ---------------------------------------------------------------------------
create extension if not exists pgcrypto;      -- gen_random_uuid, digest()
-- pg_cron is used for 2-year history retention (Phase 2). Enable it in the
-- Dashboard: Database → Extensions → enable "pg_cron". Then the cron job at the
-- bottom of this file will work.

-- ===========================================================================
-- profiles: one row per auth user (both "users" and "guardians" are profiles)
-- ===========================================================================
create table if not exists public.profiles (
  id           uuid primary key references auth.users (id) on delete cascade,
  username     text unique not null,
  display_name text,
  push_token   text,
  is_guardian  boolean not null default false,   -- signed up via Guardian login
  settings     jsonb not null default '{"graceMinutes":30,"notifyMode":"missed","approvalRequired":true}'::jsonb,
  created_at   timestamptz not null default now()
);

-- Auto-create a profile when a new auth user signs up. The username is passed
-- in auth metadata at sign-up time (options.data.username).
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, username, display_name, is_guardian)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'username', 'user_' || substr(new.id::text,1,8)),
    new.raw_user_meta_data->>'display_name',
    coalesce((new.raw_user_meta_data->>'is_guardian')::boolean, false)
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ===========================================================================
-- guardian_links: an active link = a guardian who can access a user's data.
-- At most ONE active guardian per user (Phase 1); tier raises this later.
-- ===========================================================================
create table if not exists public.guardian_links (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references public.profiles(id) on delete cascade,
  guardian_id uuid not null references public.profiles(id) on delete cascade,
  status      text not null default 'active',    -- active | deactivated
  permissions jsonb not null default '{"canView":true,"canRequestAdd":true}'::jsonb,
  created_at  timestamptz not null default now(),
  unique (user_id, guardian_id)
);
-- Enforce a single ACTIVE guardian per user:
create unique index if not exists one_active_guardian_per_user
  on public.guardian_links (user_id) where (status = 'active');

-- ===========================================================================
-- pairing_codes: 6-digit codes the user shows; guardian consumes to link.
-- ===========================================================================
create table if not exists public.pairing_codes (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references public.profiles(id) on delete cascade,
  code_hash  text not null,                       -- sha256 of the 6-digit code
  status     text not null default 'active',      -- active | consumed | revoked
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default now() + interval '30 days'
);
create index if not exists pairing_codes_user_idx on public.pairing_codes(user_id);

-- ===========================================================================
-- medicines (mirrors the current on-device shape)
-- ===========================================================================
create table if not exists public.medicines (
  id             uuid primary key default gen_random_uuid(),
  user_id        uuid not null references public.profiles(id) on delete cascade,
  name           text not null,
  form           text default 'Tablet',
  color          text default '#FFFFFF',
  times          text[] not null default '{}',    -- ['08:00','20:00']
  snooze_minutes int default 10,
  frequency      text default 'daily',            -- daily | weekly
  days_of_week   int[] default '{0,1,2,3,4,5,6}',
  tone_id        text default 'classic',
  alert_guardian boolean default true,
  photo          text,                            -- optional base64 JPEG, ~9 KB
  created_at     timestamptz not null default now()
);
create index if not exists medicines_user_idx on public.medicines(user_id);

-- Photo column for databases created before it existed.
alter table public.medicines add column if not exists photo text;
-- Hard cap so a client bug can never push a multi-MB image into a row. The app
-- compresses to ~12 000 base64 chars (see src/utils/photo.js); 60 KB of text
-- leaves plenty of headroom while still blocking an un-shrunk original.
alter table public.medicines drop constraint if exists medicines_photo_size;
alter table public.medicines add constraint medicines_photo_size
  check (photo is null or char_length(photo) <= 60000);

-- ===========================================================================
-- dose_history (2-year rolling retention — see cron at bottom)
-- ===========================================================================
create table if not exists public.dose_history (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references public.profiles(id) on delete cascade,
  medicine_id uuid references public.medicines(id) on delete cascade,
  day         date not null,
  slot        text,                                -- scheduled 'HH:MM' this dose belongs to
  status      text not null,                       -- taken | snoozed | skipped | missed
  at          timestamptz not null default now()
);
create index if not exists dose_history_user_day_idx on public.dose_history(user_id, day);

-- Slot column for databases created before it existed. A dose is identified by
-- (day, medicine, slot): without it, a morning dose being taken counts as the
-- whole day taken, so an evening dose shows as done and a missed morning dose
-- can never be reported.
alter table public.dose_history add column if not exists slot text;
create index if not exists dose_history_slot_idx
  on public.dose_history(user_id, day, medicine_id, slot);

-- ===========================================================================
-- health_readings (Phase 2 trackers: BP / sugar / cholesterol / weight …)
-- ===========================================================================
create table if not exists public.health_readings (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references public.profiles(id) on delete cascade,
  type        text not null,                       -- bp | sugar | cholesterol | weight
  values      jsonb not null,                      -- {systolic,diastolic} | {mgdl} | ...
  unit        text,
  measured_at timestamptz not null default now(),
  note        text
);
create index if not exists health_readings_user_idx on public.health_readings(user_id, type, measured_at);

-- ===========================================================================
-- action_requests: guardian-initiated changes awaiting user approval
-- ===========================================================================
create table if not exists public.action_requests (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references public.profiles(id) on delete cascade,
  guardian_id uuid not null references public.profiles(id) on delete cascade,
  kind        text not null,                       -- add_medicine | edit_medicine
  payload     jsonb not null,
  status      text not null default 'pending',     -- pending | approved | rejected
  created_at  timestamptz not null default now()
);
create index if not exists action_requests_user_idx on public.action_requests(user_id, status);

-- ===========================================================================
-- Subscriptions / payments — Phase 3/4 STUBS (schema only; no charge logic yet)
-- ===========================================================================
create table if not exists public.plans (
  id            text primary key,                  -- 'free' | 'plus' | 'family'
  name          text not null,
  price_cents   int not null default 0,
  currency      text not null default 'INR',
  interval      text not null default 'month',
  max_guardians int not null default 1,
  features      jsonb not null default '{}'::jsonb
);

create table if not exists public.subscriptions (
  id                 uuid primary key default gen_random_uuid(),
  user_id            uuid not null references public.profiles(id) on delete cascade,
  plan_id            text not null references public.plans(id),
  status             text not null default 'active', -- active | canceled | past_due
  provider           text,                            -- razorpay | stripe (Phase 4)
  provider_ref       text,
  auto_renew         boolean not null default false,
  current_period_end timestamptz,
  created_at         timestamptz not null default now()
);
create index if not exists subscriptions_user_idx on public.subscriptions(user_id);

create table if not exists public.payment_methods (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references public.profiles(id) on delete cascade,
  provider    text,
  brand       text,                                 -- visa | mastercard | upi
  last4       text,
  token_ref   text,                                 -- provider token (never raw card)
  is_default  boolean not null default false,
  created_at  timestamptz not null default now()
);

insert into public.plans (id, name, price_cents, currency, interval, max_guardians)
values ('free','Free',0,'INR','month',1)
on conflict (id) do nothing;

-- ===========================================================================
-- Helper: is auth.uid() an ACTIVE guardian of :target_user ?
-- ===========================================================================
create or replace function public.is_linked_guardian(target_user uuid)
returns boolean
language sql stable security definer set search_path = public
as $$
  select exists (
    select 1 from public.guardian_links gl
    where gl.user_id = target_user
      and gl.guardian_id = auth.uid()
      and gl.status = 'active'
  );
$$;

-- ===========================================================================
-- Row-Level Security
-- ===========================================================================
alter table public.profiles        enable row level security;
alter table public.guardian_links  enable row level security;
alter table public.pairing_codes   enable row level security;
alter table public.medicines       enable row level security;
alter table public.dose_history    enable row level security;
alter table public.health_readings enable row level security;
alter table public.action_requests enable row level security;
alter table public.subscriptions   enable row level security;
alter table public.payment_methods enable row level security;
alter table public.plans           enable row level security;

-- plans: public read-only catalog (everyone can read; nobody writes via API)
drop policy if exists plans_read_all on public.plans;
create policy plans_read_all on public.plans for select using (true);

-- profiles: read own + linked user's profile; update own
drop policy if exists profiles_select on public.profiles;
create policy profiles_select on public.profiles for select
  using (id = auth.uid() or public.is_linked_guardian(id)
         or id in (select guardian_id from public.guardian_links where user_id = auth.uid()));
drop policy if exists profiles_update on public.profiles;
create policy profiles_update on public.profiles for update using (id = auth.uid());

-- medicines / dose_history / health_readings: owner full; linked guardian read
do $$
declare t text;
begin
  foreach t in array array['medicines','dose_history','health_readings'] loop
    execute format('drop policy if exists %1$s_owner on public.%1$s;', t);
    execute format('create policy %1$s_owner on public.%1$s for all using (user_id = auth.uid()) with check (user_id = auth.uid());', t);
    execute format('drop policy if exists %1$s_guardian_read on public.%1$s;', t);
    execute format('create policy %1$s_guardian_read on public.%1$s for select using (public.is_linked_guardian(user_id));', t);
  end loop;
end $$;

-- guardian_links: user sees own; guardian sees links where they are guardian
drop policy if exists guardian_links_read on public.guardian_links;
create policy guardian_links_read on public.guardian_links for select
  using (user_id = auth.uid() or guardian_id = auth.uid());
-- (writes happen via Edge Functions using the service role, which bypasses RLS)

-- pairing_codes: only the owner can read/manage their codes
drop policy if exists pairing_codes_owner on public.pairing_codes;
create policy pairing_codes_owner on public.pairing_codes for all
  using (user_id = auth.uid()) with check (user_id = auth.uid());

-- action_requests: user (owner) reads+updates; guardian inserts+reads own
drop policy if exists action_requests_user on public.action_requests;
create policy action_requests_user on public.action_requests for all
  using (user_id = auth.uid()) with check (user_id = auth.uid());
drop policy if exists action_requests_guardian on public.action_requests;
create policy action_requests_guardian on public.action_requests for select
  using (guardian_id = auth.uid());
drop policy if exists action_requests_guardian_insert on public.action_requests;
create policy action_requests_guardian_insert on public.action_requests for insert
  with check (guardian_id = auth.uid() and public.is_linked_guardian(user_id));

-- subscriptions / payment_methods: owner only
drop policy if exists subscriptions_owner on public.subscriptions;
create policy subscriptions_owner on public.subscriptions for all
  using (user_id = auth.uid()) with check (user_id = auth.uid());
drop policy if exists payment_methods_owner on public.payment_methods;
create policy payment_methods_owner on public.payment_methods for all
  using (user_id = auth.uid()) with check (user_id = auth.uid());

-- ===========================================================================
-- 2-year history retention + all security hardening: see hardening.sql, which
-- must be run after this file, pairing.sql and subscriptions.sql.
-- ===========================================================================


-- ========================================================================
-- pairing.sql
-- ========================================================================

-- PillReminder — Phase 1 guardian pairing (RPC, no Edge Functions needed)
-- Run this in the Supabase SQL Editor AFTER schema.sql. Safe to re-run.

-- The user calls this to create a fresh 6-digit pairing code to hand to a
-- guardian. Revokes any previous unused codes. Returns the plaintext code once.
create or replace function public.generate_pairing_code()
returns text
language plpgsql security definer set search_path = public, extensions
as $$
declare
  new_code text;
begin
  if auth.uid() is null then raise exception 'not authenticated'; end if;
  update public.pairing_codes set status = 'revoked'
    where user_id = auth.uid() and status = 'active';
  new_code := lpad((floor(random() * 1000000))::int::text, 6, '0');
  insert into public.pairing_codes (user_id, code_hash, status, expires_at)
    values (auth.uid(),
            encode(digest(new_code, 'sha256'), 'hex'),
            'active',
            now() + interval '30 days');
  return new_code;
end;
$$;

-- A guardian calls this with the user's username + the 6-digit code. Validates,
-- consumes the code, deactivates any prior guardian (single-guardian rule), and
-- creates the active link. Raises on bad username/code/self-pair.
create or replace function public.pair_with_code(target_username text, code text)
returns json
language plpgsql security definer set search_path = public, extensions
as $$
declare
  target_id uuid;
  pc        record;
  gid       uuid := auth.uid();
begin
  if gid is null then raise exception 'not authenticated'; end if;

  select id into target_id from public.profiles
    where lower(username) = lower(target_username);
  if target_id is null then raise exception 'user not found'; end if;
  if target_id = gid then raise exception 'cannot pair with yourself'; end if;

  select * into pc from public.pairing_codes
    where user_id = target_id
      and status = 'active'
      and code_hash = encode(digest(code, 'sha256'), 'hex')
      and expires_at > now()
    order by created_at desc
    limit 1;
  if pc is null then raise exception 'invalid or expired code'; end if;

  -- single active guardian per user: retire the previous one
  update public.guardian_links set status = 'deactivated'
    where user_id = target_id and status = 'active';

  update public.pairing_codes set status = 'consumed' where id = pc.id;

  insert into public.guardian_links (user_id, guardian_id, status)
    values (target_id, gid, 'active')
    on conflict (user_id, guardian_id) do update set status = 'active';

  return json_build_object('user_id', target_id, 'username', target_username);
end;
$$;

-- The user calls this to drop their current guardian and invalidate codes.
create or replace function public.revoke_guardian()
returns void
language plpgsql security definer set search_path = public, extensions
as $$
begin
  if auth.uid() is null then raise exception 'not authenticated'; end if;
  update public.guardian_links set status = 'deactivated'
    where user_id = auth.uid() and status = 'active';
  update public.pairing_codes set status = 'revoked'
    where user_id = auth.uid() and status = 'active';
end;
$$;

grant execute on function public.generate_pairing_code()            to authenticated;
grant execute on function public.pair_with_code(text, text)         to authenticated;
grant execute on function public.revoke_guardian()                  to authenticated;


-- ========================================================================
-- subscriptions.sql
-- ========================================================================

-- PillReminder — Phase 3 subscriptions + multi-guardian tiers.
-- Run in the Supabase SQL Editor AFTER schema.sql and pairing.sql. Re-runnable.

-- Seed the plan catalog (free already inserted by schema.sql).
insert into public.plans (id, name, price_cents, currency, interval, max_guardians, features) values
  ('plus',   'Plus',   9900,  'INR', 'month', 3, '{"trackers":true,"historyYears":2}'::jsonb),
  ('family', 'Family', 19900, 'INR', 'month', 5, '{"trackers":true,"historyYears":2}'::jsonb)
on conflict (id) do update
  set name = excluded.name,
      price_cents = excluded.price_cents,
      max_guardians = excluded.max_guardians,
      features = excluded.features;

-- Multi-guardian: drop the strict single-active-guardian index; the pairing RPC
-- now enforces the per-plan limit instead.
drop index if exists public.one_active_guardian_per_user;

-- Helper: how many guardians is this user allowed (by their active plan)?
create or replace function public.guardian_limit(target_user uuid)
returns int
language sql stable security definer set search_path = public
as $$
  select coalesce(
    (select p.max_guardians
       from public.subscriptions s
       join public.plans p on p.id = s.plan_id
      where s.user_id = target_user and s.status = 'active'
      order by p.max_guardians desc
      limit 1),
    1);  -- default: free plan = 1 guardian
$$;

-- Replace pair_with_code to honour the plan limit.
--  * limit == 1  → new guardian REPLACES the old (change-guardian flow)
--  * limit  > 1  → add up to the limit, then reject with a clear message
create or replace function public.pair_with_code(target_username text, code text)
returns json
language plpgsql security definer set search_path = public, extensions
as $$
declare
  target_id uuid;
  pc        record;
  gid       uuid := auth.uid();
  lim       int;
  active_ct int;
begin
  if gid is null then raise exception 'not authenticated'; end if;

  select id into target_id from public.profiles
    where lower(username) = lower(target_username);
  if target_id is null then raise exception 'user not found'; end if;
  if target_id = gid then raise exception 'cannot pair with yourself'; end if;

  select * into pc from public.pairing_codes
    where user_id = target_id and status = 'active'
      and code_hash = encode(digest(code, 'sha256'), 'hex')
      and expires_at > now()
    order by created_at desc limit 1;
  if pc is null then raise exception 'invalid or expired code'; end if;

  lim := public.guardian_limit(target_id);
  select count(*) into active_ct from public.guardian_links
    where user_id = target_id and status = 'active' and guardian_id <> gid;

  if active_ct >= lim then
    if lim = 1 then
      update public.guardian_links set status = 'deactivated'
        where user_id = target_id and status = 'active';   -- replace
    else
      raise exception 'guardian limit reached (%). Ask them to remove one or upgrade.', lim;
    end if;
  end if;

  update public.pairing_codes set status = 'consumed' where id = pc.id;

  insert into public.guardian_links (user_id, guardian_id, status)
    values (target_id, gid, 'active')
    on conflict (user_id, guardian_id) do update set status = 'active';

  return json_build_object('user_id', target_id, 'username', target_username);
end;
$$;

grant execute on function public.guardian_limit(uuid) to authenticated;
grant execute on function public.pair_with_code(text, text) to authenticated;


-- ========================================================================
-- hardening.sql
-- ========================================================================

-- PillReminder — security hardening.
-- Run in the Supabase SQL Editor AFTER schema.sql, pairing.sql and
-- subscriptions.sql. Safe to re-run.
--
-- Closes SEC-01 through SEC-04, DB-01 and DB-02 from docs/audit-report.md.
-- The premise throughout: the client is untrusted. The anon key ships inside a
-- decompilable APK, so anything the client is allowed to write, an attacker is
-- allowed to write.

-- ===========================================================================
-- SEC-01 — subscriptions must not be client-writable
--
-- Previously `subscriptions_owner ... for all` let any signed-in user insert an
-- active row for the 'family' plan and get the paid tier (and its raised
-- guardian limit) for free. Reads stay; writes move to the service role, which
-- is only reachable from an Edge Function invoked by a verified payment webhook.
-- ===========================================================================
drop policy if exists subscriptions_owner on public.subscriptions;

drop policy if exists subscriptions_read_own on public.subscriptions;
create policy subscriptions_read_own on public.subscriptions
  for select using (user_id = auth.uid());

-- Same reasoning for stored payment methods: the client may look, never write.
drop policy if exists payment_methods_owner on public.payment_methods;

drop policy if exists payment_methods_read_own on public.payment_methods;
create policy payment_methods_read_own on public.payment_methods
  for select using (user_id = auth.uid());

-- Nobody reaches these tables through PostgREST with the anon key at all.
revoke insert, update, delete on public.subscriptions   from anon, authenticated;
revoke insert, update, delete on public.payment_methods from anon, authenticated;

-- ===========================================================================
-- SEC-02 — cap the guardian request payload
--
-- medicines.photo is capped at 60 000 chars, but action_requests.payload is
-- unconstrained jsonb and the request flow puts a photo inside it. A malicious
-- or buggy guardian client could write arbitrarily large blobs into a patient's
-- row.
-- ===========================================================================
alter table public.action_requests
  drop constraint if exists action_requests_payload_size;
alter table public.action_requests
  add constraint action_requests_payload_size
  check (pg_column_size(payload) <= 80000);

-- ===========================================================================
-- SEC-03 — a user may edit their own profile, but not every column
--
-- `profiles_update ... using (id = auth.uid())` allowed changing `username`
-- (the identifier guardians pair against) and `is_guardian` (which decides
-- which flow the app enters). Only display_name, push_token and settings are
-- the user's to change.
-- ===========================================================================
create or replace function public.guard_profile_columns()
returns trigger
language plpgsql security definer set search_path = public
as $$
begin
  -- The service role bypasses RLS and is trusted; only constrain end users.
  if auth.uid() is null then
    return new;
  end if;
  new.id          := old.id;
  new.username    := old.username;
  new.is_guardian := old.is_guardian;
  new.created_at  := old.created_at;
  return new;
end;
$$;

drop trigger if exists profiles_guard_columns on public.profiles;
create trigger profiles_guard_columns
  before update on public.profiles
  for each row execute function public.guard_profile_columns();

-- ===========================================================================
-- SEC-04 — pairing: one generic error, and a real attempt limit
--
-- The old function distinguished 'user not found' from 'invalid or expired
-- code', which let any signed-in user enumerate accounts. It also had no
-- attempt counter against a 10^6 keyspace with 30-day codes.
-- ===========================================================================
create table if not exists public.pairing_attempts (
  id         uuid primary key default gen_random_uuid(),
  guardian_id uuid not null references public.profiles(id) on delete cascade,
  target_username text not null,
  succeeded  boolean not null default false,
  at         timestamptz not null default now()
);
create index if not exists pairing_attempts_guardian_idx
  on public.pairing_attempts(guardian_id, at);

alter table public.pairing_attempts enable row level security;
-- No policy at all: only the security-definer function below touches this.
revoke all on public.pairing_attempts from anon, authenticated;

create or replace function public.pair_with_code(target_username text, code text)
returns json
language plpgsql security definer set search_path = public, extensions
as $$
declare
  target_id uuid;
  pc        record;
  gid       uuid := auth.uid();
  lim       int;
  active_ct int;
  recent_failures int;
  -- One message for every rejection, so nothing distinguishes "no such user"
  -- from "wrong code".
  generic_error constant text := 'That username and code do not match. Ask them to generate a new code.';
begin
  if gid is null then raise exception 'not authenticated'; end if;

  -- Rate limit: 10 failures in 15 minutes locks this guardian out of pairing.
  select count(*) into recent_failures
    from public.pairing_attempts
   where guardian_id = gid
     and succeeded = false
     and at > now() - interval '15 minutes';
  if recent_failures >= 10 then
    raise exception 'Too many attempts. Try again in 15 minutes.';
  end if;

  select id into target_id from public.profiles
    where lower(username) = lower(target_username);

  if target_id is null or target_id = gid then
    insert into public.pairing_attempts (guardian_id, target_username)
      values (gid, target_username);
    raise exception '%', generic_error;
  end if;

  select * into pc from public.pairing_codes
    where user_id = target_id and status = 'active'
      and code_hash = encode(digest(code, 'sha256'), 'hex')
      and expires_at > now()
    order by created_at desc limit 1;
  if pc is null then
    insert into public.pairing_attempts (guardian_id, target_username)
      values (gid, target_username);
    raise exception '%', generic_error;
  end if;

  lim := public.guardian_limit(target_id);
  select count(*) into active_ct from public.guardian_links
    where user_id = target_id and status = 'active' and guardian_id <> gid;

  if active_ct >= lim then
    if lim = 1 then
      update public.guardian_links set status = 'deactivated'
        where user_id = target_id and status = 'active';   -- replace
    else
      raise exception 'guardian limit reached (%). Ask them to remove one or upgrade.', lim;
    end if;
  end if;

  update public.pairing_codes set status = 'consumed' where id = pc.id;

  insert into public.guardian_links (user_id, guardian_id, status)
    values (target_id, gid, 'active')
    on conflict (user_id, guardian_id) do update set status = 'active';

  insert into public.pairing_attempts (guardian_id, target_username, succeeded)
    values (gid, target_username, true);

  return json_build_object('user_id', target_id, 'username', target_username);
end;
$$;

grant execute on function public.pair_with_code(text, text) to authenticated;

-- ===========================================================================
-- DB-01 — `values` is a reserved SQL keyword
--
-- It works through PostgREST but breaks any hand-written SQL that does not
-- quote it. Renamed while the table is still small. Idempotent.
-- ===========================================================================
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'health_readings'
      and column_name = 'values'
  ) then
    alter table public.health_readings rename column "values" to reading_values;
  end if;
end $$;

-- ===========================================================================
-- DB-02 — 2-year retention, enforced by the server
--
-- The client-side pruneOldHistory() only runs when a user opens the app, so a
-- lapsed user kept their history forever. Requires the pg_cron extension:
-- Dashboard -> Database -> Extensions -> enable "pg_cron".
-- ===========================================================================
do $$
begin
  if exists (select 1 from pg_extension where extname = 'pg_cron') then
    perform cron.unschedule('prune-dose-history')
      where exists (select 1 from cron.job where jobname = 'prune-dose-history');
    perform cron.schedule(
      'prune-dose-history',
      '0 3 * * *',
      $job$ delete from public.dose_history where day < (current_date - interval '2 years'); $job$
    );
  else
    raise notice 'pg_cron is not enabled — server-side retention was NOT scheduled.';
  end if;
end $$;


-- ========================================================================
-- onboarding.sql
-- ========================================================================

-- PillReminder — registration, phone verification and profile details.
-- Run in the Supabase SQL Editor AFTER schema.sql, pairing.sql,
-- subscriptions.sql and hardening.sql. Safe to re-run.
--
-- Model: patient and guardian remain SEPARATE account types, and a phone number
-- may hold at most one of each. That is why the phone lives here rather than on
-- auth.users, whose `phone` column is globally unique and would block the
-- common case of one carer who also takes their own medicine.
--
-- Consequence: OTP cannot use Supabase's built-in phone auth. It runs through
-- the Edge Functions in supabase/functions/, which hold the service role. The
-- client never writes a verified phone and never creates its own account.

-- ===========================================================================
-- Profile details
--
-- Date of birth, not age: an age is wrong within a year and carries no record
-- of when it was true. Height in centimetres, not feet: one canonical unit,
-- rendered per the user's preference.
--
-- Weight is deliberately ABSENT. It already lives in public.health_readings
-- with a full history and trend; a second copy here would disagree with it
-- within a month. The signup value seeds the first reading instead.
-- ===========================================================================
alter table public.profiles add column if not exists phone             text;
alter table public.profiles add column if not exists phone_verified_at timestamptz;
alter table public.profiles add column if not exists full_name         text;
alter table public.profiles add column if not exists gender            text;
alter table public.profiles add column if not exists date_of_birth     date;
alter table public.profiles add column if not exists height_cm         numeric(5,1);
alter table public.profiles add column if not exists country           text;
-- Non-null once the details step has been completed OR skipped, so the app
-- knows never to ask again.
alter table public.profiles add column if not exists onboarded_at      timestamptz;

alter table public.profiles drop constraint if exists profiles_gender_check;
alter table public.profiles add constraint profiles_gender_check
  check (gender is null or gender in ('female', 'male', 'other', 'undisclosed'));

alter table public.profiles drop constraint if exists profiles_height_check;
alter table public.profiles add constraint profiles_height_check
  check (height_cm is null or (height_cm > 30 and height_cm < 280));

alter table public.profiles drop constraint if exists profiles_dob_check;
alter table public.profiles add constraint profiles_dob_check
  check (date_of_birth is null
         or (date_of_birth > date '1900-01-01' and date_of_birth <= current_date));

alter table public.profiles drop constraint if exists profiles_phone_check;
alter table public.profiles add constraint profiles_phone_check
  check (phone is null or phone ~ '^\+[1-9][0-9]{7,14}$');   -- E.164

-- ONE patient account and ONE guardian account per number. A carer registering
-- their own patient account and a guardian account on the same phone is the
-- case this is built for.
drop index if exists public.profiles_phone_per_role;
create unique index profiles_phone_per_role
  on public.profiles (phone, is_guardian)
  where phone is not null;

-- ===========================================================================
-- Phone verification
--
-- Only the Edge Functions touch this table. No RLS policy is defined at all,
-- so the anon and authenticated roles can read nothing even by accident.
-- ===========================================================================
create table if not exists public.phone_verifications (
  id           uuid primary key default gen_random_uuid(),
  phone        text not null,
  is_guardian  boolean not null,
  code_hash    text not null,
  attempts     int not null default 0,
  consumed_at  timestamptz,
  -- Handed to the client on success and required to create the account, so a
  -- verified number cannot be swapped for an unverified one at the last step.
  claim_token  uuid not null default gen_random_uuid(),
  claimed_at   timestamptz,
  expires_at   timestamptz not null default now() + interval '10 minutes',
  created_at   timestamptz not null default now(),
  requested_ip text
);
create index if not exists phone_verifications_lookup_idx
  on public.phone_verifications (phone, is_guardian, created_at desc);

alter table public.phone_verifications enable row level security;
revoke all on public.phone_verifications from anon, authenticated;

-- ===========================================================================
-- Username availability
--
-- Every signup form needs this, and it necessarily confirms whether a name is
-- taken. That is a different exposure from the pairing oracle closed in
-- hardening.sql (SEC-04): this reveals only that a name exists, never ties a
-- name to a phone, and gives no foothold for guessing a pairing code. Rate
-- limiting is what keeps it from becoming a bulk enumeration tool.
-- ===========================================================================
create or replace function public.username_available(candidate text)
returns boolean
language sql stable security definer set search_path = public
as $$
  select not exists (
    select 1 from public.profiles
    where lower(username) = lower(trim(candidate))
  );
$$;

grant execute on function public.username_available(text) to anon, authenticated;

-- Is this number already used by an account of this role?
create or replace function public.phone_available(candidate text, want_guardian boolean)
returns boolean
language sql stable security definer set search_path = public
as $$
  select not exists (
    select 1 from public.profiles
    where phone = candidate and is_guardian = want_guardian
  );
$$;

grant execute on function public.phone_available(text, boolean) to anon, authenticated;

-- ===========================================================================
-- Column guard: extend the SEC-03 trigger to cover the new identity columns.
--
-- A user may edit their own name, gender, date of birth, height and country.
-- They may NOT rewrite their username, role, or — crucially — their phone or
-- its verified timestamp, because the phone is a recovery credential. Changing
-- it goes through a fresh OTP and the Edge Function, never a direct update.
-- ===========================================================================
create or replace function public.guard_profile_columns()
returns trigger
language plpgsql security definer set search_path = public
as $$
begin
  -- The service role bypasses RLS and is trusted; only constrain end users.
  if auth.uid() is null then
    return new;
  end if;
  new.id                := old.id;
  new.username          := old.username;
  new.is_guardian       := old.is_guardian;
  new.created_at        := old.created_at;
  new.phone             := old.phone;
  new.phone_verified_at := old.phone_verified_at;
  return new;
end;
$$;

drop trigger if exists profiles_guard_columns on public.profiles;
create trigger profiles_guard_columns
  before update on public.profiles
  for each row execute function public.guard_profile_columns();

-- ===========================================================================
-- Retention: verification rows are short-lived and contain a phone number.
-- Keep them only as long as the rate-limit window needs.
-- ===========================================================================
do $$
begin
  if exists (select 1 from pg_extension where extname = 'pg_cron') then
    perform cron.unschedule('prune-phone-verifications')
      where exists (select 1 from cron.job where jobname = 'prune-phone-verifications');
    perform cron.schedule(
      'prune-phone-verifications',
      '15 * * * *',
      $job$ delete from public.phone_verifications where created_at < now() - interval '24 hours'; $job$
    );
  else
    raise notice 'pg_cron is not enabled — verification rows will NOT be pruned automatically.';
  end if;
end $$;


-- ========================================================================
-- course.sql
-- ========================================================================

-- Course length: "take this for 15 days".
--
-- A prescription is usually finite — an antibiotic for 7 days, a steroid taper
-- for 10 — and an alarm that keeps firing after the course has finished trains
-- people to ignore it, which is the one thing this app cannot afford.
--
-- Stored as two dates rather than a day count so the end never drifts: a count
-- has to be resolved against a start every time it is read, and any disagreement
-- about which day is "day 1" moves the end date.
--
-- end_date NULL means ongoing, which stays the default — most long-term
-- medicines genuinely have no end.

-- Existing medicines start on the day they were ADDED, not the day this ran:
-- stamping "today" on them hid their whole history from the calendar.
alter table public.medicines
  add column if not exists start_date date;
update public.medicines set start_date = created_at::date where start_date is null;
alter table public.medicines alter column start_date set default current_date;
alter table public.medicines alter column start_date set not null;

alter table public.medicines
  add column if not exists end_date date;

-- A course that ends before it starts would silently never be due.
alter table public.medicines drop constraint if exists medicines_course_order;
alter table public.medicines
  add constraint medicines_course_order
  check (end_date is null or end_date >= start_date);

comment on column public.medicines.start_date is
  'First day of the course. Defaults to the day the medicine was added.';
comment on column public.medicines.end_date is
  'Last day INCLUSIVE. NULL means ongoing with no planned end.';


-- ========================================================================
-- guardian_readings.sql
-- ========================================================================

-- A linked guardian may record a health reading (BP, sugar, weight, …) for the
-- person they look after — at a clinic visit, say. Run after schema.sql and
-- hardening.sql. Re-runnable.
--
-- The reading still belongs to the person (user_id is theirs); recorded_by
-- says who entered it. The guardian may only ADD: edits and deletions stay
-- with the owner, under the existing health_readings_owner policy.

alter table public.health_readings
  add column if not exists recorded_by uuid references public.profiles(id) on delete set null;

drop policy if exists health_readings_guardian_insert on public.health_readings;
create policy health_readings_guardian_insert on public.health_readings for insert
  with check (public.is_linked_guardian(user_id) and recorded_by = auth.uid());

notify pgrst, 'reload schema';


-- ===========================================================================
-- Verification. Every row should read OK.
-- ===========================================================================
select 'dose_history.slot (per-dose tracking)' as check,
       case when exists (select 1 from information_schema.columns
         where table_name = 'dose_history' and column_name = 'slot')
       then 'OK' else 'MISSING' end as status
union all
select 'medicines.photo',
       case when exists (select 1 from information_schema.columns
         where table_name = 'medicines' and column_name = 'photo')
       then 'OK' else 'MISSING' end
union all
select 'health_readings.reading_values (renamed from `values`)',
       case when exists (select 1 from information_schema.columns
         where table_name = 'health_readings' and column_name = 'reading_values')
       then 'OK' else 'MISSING' end
union all
select 'profiles.phone + onboarding fields',
       case when exists (select 1 from information_schema.columns
         where table_name = 'profiles' and column_name = 'onboarded_at')
       then 'OK' else 'MISSING' end
union all
select 'phone_verifications table',
       case when to_regclass('public.phone_verifications') is not null
       then 'OK' else 'MISSING' end
union all
select 'one phone per role (unique index)',
       case when exists (select 1 from pg_indexes
         where indexname = 'profiles_phone_per_role')
       then 'OK' else 'MISSING' end
union all
select 'SEC-01: subscriptions NOT client-writable',
       case when not exists (select 1 from pg_policies
         where tablename = 'subscriptions' and cmd = 'INSERT')
       then 'OK' else 'STILL WRITABLE' end
union all
select 'SEC-03: profile column guard trigger',
       case when exists (select 1 from pg_trigger
         where tgname = 'profiles_guard_columns')
       then 'OK' else 'MISSING' end
union all
select 'SEC-04: pairing attempt log',
       case when to_regclass('public.pairing_attempts') is not null
       then 'OK' else 'MISSING' end
union all
select 'medicines.end_date (course length)',
       case when exists (select 1 from information_schema.columns
         where table_name = 'medicines' and column_name = 'end_date')
       then 'OK' else 'MISSING' end
union all
select 'pg_cron enabled (retention jobs)',
       case when exists (select 1 from pg_extension where extname = 'pg_cron')
       then 'OK' else 'NOT ENABLED - retention was skipped' end;
