#!/usr/bin/env node
/* eslint-disable no-console */
//
// Concatenates the migrations into supabase/all.sql, in dependency order, with
// a verification query on the end.
//
//   npm run sql
//
// The individual files stay the source of truth — this exists so that setting
// up a database is one paste into the SQL Editor instead of five, and so the
// order can't be got wrong.

const fs = require('fs');
const path = require('path');

const DIR = path.resolve(__dirname, '..', 'supabase');

// Order is load-bearing: each file depends on tables the previous ones create.
const ORDER = [
  'schema.sql',
  'pairing.sql',
  'subscriptions.sql',
  'hardening.sql',
  'onboarding.sql',
  'course.sql',
  'guardian_readings.sql',
];

const HEADER = `-- PillReminder — every migration, in dependency order, as one script.
--
-- Generated by scripts/build-sql.js. Do not edit: change the individual files
-- and regenerate with \`npm run sql\`.
--
-- WHERE TO RUN THIS
--   Supabase Dashboard -> SQL Editor -> New query -> paste -> Run.
--
-- BEFORE YOU RUN IT
--   Enable pg_cron first: Database -> Extensions -> search "pg_cron" -> enable.
--   Without it the two retention jobs are skipped with a NOTICE rather than
--   failing, so the script still completes — you just get no server-side
--   pruning of dose history or expired verification codes.
--
-- Safe to re-run: every statement is guarded with \`if not exists\`,
-- \`create or replace\`, or a \`drop ... if exists\` first.
`;

// Reads as a checklist in the SQL Editor's results pane: every row should be OK.
const VERIFY = `

-- ===========================================================================
-- Verification. Every row should read OK.
-- ===========================================================================
select 'dose_history.slot (per-dose tracking)' as check,
       case when exists (select 1 from information_schema.columns
         where table_name = 'dose_history' and column_name = 'slot')
       then 'OK' else 'MISSING' end as status
union all
select 'medicines.photo',
       case when exists (select 1 from information_schema.columns
         where table_name = 'medicines' and column_name = 'photo')
       then 'OK' else 'MISSING' end
union all
select 'health_readings.reading_values (renamed from \`values\`)',
       case when exists (select 1 from information_schema.columns
         where table_name = 'health_readings' and column_name = 'reading_values')
       then 'OK' else 'MISSING' end
union all
select 'profiles.phone + onboarding fields',
       case when exists (select 1 from information_schema.columns
         where table_name = 'profiles' and column_name = 'onboarded_at')
       then 'OK' else 'MISSING' end
union all
select 'phone_verifications table',
       case when to_regclass('public.phone_verifications') is not null
       then 'OK' else 'MISSING' end
union all
select 'one phone per role (unique index)',
       case when exists (select 1 from pg_indexes
         where indexname = 'profiles_phone_per_role')
       then 'OK' else 'MISSING' end
union all
select 'SEC-01: subscriptions NOT client-writable',
       case when not exists (select 1 from pg_policies
         where tablename = 'subscriptions' and cmd = 'INSERT')
       then 'OK' else 'STILL WRITABLE' end
union all
select 'SEC-03: profile column guard trigger',
       case when exists (select 1 from pg_trigger
         where tgname = 'profiles_guard_columns')
       then 'OK' else 'MISSING' end
union all
select 'SEC-04: pairing attempt log',
       case when to_regclass('public.pairing_attempts') is not null
       then 'OK' else 'MISSING' end
union all
select 'medicines.end_date (course length)',
       case when exists (select 1 from information_schema.columns
         where table_name = 'medicines' and column_name = 'end_date')
       then 'OK' else 'MISSING' end
union all
select 'pg_cron enabled (retention jobs)',
       case when exists (select 1 from pg_extension where extname = 'pg_cron')
       then 'OK' else 'NOT ENABLED - retention was skipped' end;
`;

function main() {
  const parts = [HEADER];

  for (const name of ORDER) {
    const file = path.join(DIR, name);
    if (!fs.existsSync(file)) {
      console.error(`Missing migration: supabase/${name}`);
      process.exit(1);
    }
    const rule = '-- ' + '='.repeat(72);
    parts.push(`\n\n${rule}\n-- ${name}\n${rule}\n\n${fs.readFileSync(file, 'utf8')}`);
  }

  parts.push(VERIFY);

  const out = path.join(DIR, 'all.sql');
  fs.writeFileSync(out, parts.join(''));

  const text = fs.readFileSync(out, 'utf8');
  console.log(`supabase/all.sql — ${text.split('\n').length} lines, ${Math.round(text.length / 1024)} KB`);
  console.log(`Order: ${ORDER.join(' -> ')}`);
  console.log('\nPaste it into the Supabase SQL Editor and run it.');
}

main();
